### ISSUE TITLE
Connector Waston [Version missing]

### ISSUE THREAD

**Issue by ki-wwi** [codeforequity-at/botium-box-basic-dist#1]
Bei "Register new chatbot" wollten wir eine Verbindung zum Watson Assistant herstellen. Wir erhalten folgenden Fehler beim Anlegen

`Error: Missing 'version' query parameter
    at Request._callback (/app/server/node_modules/watson-developer-cloud/lib/requestwrapper.js:102:21)
    at Request.self.callback (/app/server/node_modules/watson-developer-cloud/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.<anonymous> (/app/server/node_modules/watson-developer-cloud/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:188:13)
    at Gunzip.<anonymous> (/app/server/node_modules/watson-developer-cloud/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:276:13)
    at Gunzip.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)`

Die von uns eingegebenen Credentials sind korrekt, da wir den Watson Assistant testen können (durch dieses Tutorial: https://chatbotsmagazine.com/5-steps-automated-testing-of-chatbots-in-eclipse-ef4c3dcaf233)

Is the support language german or should we translate it?

**Comment by codeforequity-at** [comment]
Hallo,
Das dürfte etwas mit der inkludierten Watson-Bibliothek zu tun haben. Wir haben in unserer Entwicklung bereits das Paket "watson-developer-cloud" auf 3.15.2 hochgezogen, damit funktioniert die Anbindung wieder. Bis wir das publishen dauert es noch eine Woche. Als Quick-Fix kann man in web/server/package.json die Version von Hand anpassen, gefolgt von "npm install".

**Comment by codeforequity-at** [comment]
Ist teil von 1.1.3.
