### ISSUE TITLE
Botium box issue with redis servers

### ISSUE THREAD

**Issue by vlntdds** [codeforequity-at/botium-box-basic-dist#23]
Already tested Elasticache, Redis Cloud, Redis solutions on heroku but always get the same exception:

```
2019-07-09T01:57:46.505435+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
2019-07-09T01:57:46.505437+00:00 app[web.1]:     at parseError (/app/server/node_modules/redis-parser/lib/parser.js:179:12)
2019-07-09T01:57:46.505439+00:00 app[web.1]:     at parseType (/app/server/node_modules/redis-parser/lib/parser.js:302:14)
```

And this keeps going and going, the URL is ok, since i can connect via redis-cli on my machine and on heroku container.

**Comment by vlntdds** [comment]
Full logs with debug:

```
2019-07-09T02:03:52.283620+00:00 heroku[web.1]: Starting process with command `npm start`
2019-07-09T02:03:54.442450+00:00 app[web.1]: 
2019-07-09T02:03:54.442473+00:00 app[web.1]: > botium-box@1.7.2 start /app
2019-07-09T02:03:54.442475+00:00 app[web.1]: > npm-run-all -p start:agent start:server
2019-07-09T02:03:54.442477+00:00 app[web.1]: 
2019-07-09T02:03:55.225226+00:00 app[web.1]: 
2019-07-09T02:03:55.225271+00:00 app[web.1]: > botium-box@1.7.2 start:agent /app
2019-07-09T02:03:55.225274+00:00 app[web.1]: > cd agent && npm run start:dist
2019-07-09T02:03:55.225276+00:00 app[web.1]: 
2019-07-09T02:03:55.235766+00:00 app[web.1]: 
2019-07-09T02:03:55.235770+00:00 app[web.1]: > botium-box@1.7.2 start:server /app
2019-07-09T02:03:55.235773+00:00 app[web.1]: > cd server && npm run start:dist
2019-07-09T02:03:55.235775+00:00 app[web.1]: 
2019-07-09T02:03:55.649226+00:00 app[web.1]: 
2019-07-09T02:03:55.649243+00:00 app[web.1]: > botium-box-agent@1.0.0 start:dist /app/agent
2019-07-09T02:03:55.649245+00:00 app[web.1]: > DEBUG=* node dist/botium-box-agent.js
2019-07-09T02:03:55.649247+00:00 app[web.1]: 
2019-07-09T02:03:55.656826+00:00 app[web.1]: 
2019-07-09T02:03:55.656831+00:00 app[web.1]: > botium-box-server@1.0.0 start:dist /app/server
2019-07-09T02:03:55.656833+00:00 app[web.1]: > DEBUG=* node dist/botium-box-server.js
2019-07-09T02:03:55.656835+00:00 app[web.1]: 
2019-07-09T02:03:55.899851+00:00 app[web.1]: BOTIUM BOX - AGENT
2019-07-09T02:03:55.901179+00:00 app[web.1]: BUILD_TARGET: COMMUNITY EDITION
2019-07-09T02:03:55.901287+00:00 app[web.1]: BUILD_BRANCH: release/1.7.2
2019-07-09T02:03:55.901291+00:00 app[web.1]: BUILD_REVISION: 10496eafe058947a3d402ac7eda45308e8110f8e
2019-07-09T02:03:55.901293+00:00 app[web.1]: BUILD_TIMESTAMP: 2019-06-27T00:02:53+02:00
2019-07-09T02:03:55.901484+00:00 app[web.1]: BOTIUMBOX_QUEUE_REDISURL: redis://rediscloud:****@****.cloud.redislabs.com:17618
2019-07-09T02:03:55.902209+00:00 app[web.1]: 2019-07-09T02:03:55.901Z botium-box-worker Connecting agent Default Agent to group Default Group ...
2019-07-09T02:03:55.902330+00:00 app[web.1]: 2019-07-09T02:03:55.902Z botium-box-worker connecting to Botium queue '{"prefix":"qbasic","redis":"redis://rediscloud:****@****.com:17618"}'
2019-07-09T02:03:55.902449+00:00 app[web.1]: 2019-07-09T02:03:55.902Z botium-box-worker Using job progress retryAttempts: 5, retryDelay: 10000
2019-07-09T02:03:55.916763+00:00 app[web.1]: 2019-07-09T02:03:55.916Z botium-box-worker Trying to register agent ...
2019-07-09T02:03:59.179855+00:00 app[web.1]: BOTIUM BOX - SERVER
2019-07-09T02:03:59.180326+00:00 app[web.1]: BUILD_TARGET: COMMUNITY EDITION
2019-07-09T02:03:59.180454+00:00 app[web.1]: BUILD_BRANCH: release/1.7.2
2019-07-09T02:03:59.180458+00:00 app[web.1]: BUILD_REVISION: 10496eafe058947a3d402ac7eda45308e8110f8e
2019-07-09T02:03:59.180460+00:00 app[web.1]: BUILD_TIMESTAMP: 2019-06-27T00:02:57+02:00
2019-07-09T02:03:59.180542+00:00 app[web.1]: PRISMA_ENDPOINT: https://****.herokuapp.com
2019-07-09T02:03:59.180626+00:00 app[web.1]: BOTIUMBOX_QUEUE_REDISURL: redis://rediscloud:******@redis-*****.redislabs.com:17618
2019-07-09T02:03:59.181677+00:00 app[web.1]: 2019-07-09T02:03:59.181Z botium-box-server-index connecting to Botium queue '{"prefix":"qbasic","redis":"redis://rediscloud:****@redis-****.cloud.redislabs.com:17618"}'
2019-07-09T02:03:59.192650+00:00 app[web.1]: 2019-07-09T02:03:59.192Z botium-box-server-index Using BOTIUM_TEMPDIR ./botiumwork
2019-07-09T02:03:59.192815+00:00 app[web.1]: 2019-07-09T02:03:59.192Z botium-box-server-index Using TESTSETDIR ./testsets
2019-07-09T02:04:00.292314+00:00 app[web.1]: 2019-07-09T02:04:00.292Z botium-box-testset-scanner scanDirForTestSets scanning testsets ...
2019-07-09T02:04:00.296383+00:00 app[web.1]: 2019-07-09T02:04:00.296Z ioredis:redis status[****.com:17618]: [empty] -> connecting
2019-07-09T02:04:00.297226+00:00 app[web.1]: 2019-07-09T02:04:00.297Z ioredis:redis status[****s.com:17618]: [empty] -> connecting
2019-07-09T02:04:00.298156+00:00 app[web.1]: 2019-07-09T02:04:00.298Z botium-box-server-index Using Prisma Endpoint https://****
2019-07-09T02:04:00.300698+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "x-powered-by" to true
2019-07-09T02:04:00.300832+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "etag" to 'weak'
2019-07-09T02:04:00.301134+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "etag fn" to [Function: generateETag]
2019-07-09T02:04:00.301222+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "env" to 'production'
2019-07-09T02:04:00.301307+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "query parser" to 'extended'
2019-07-09T02:04:00.301440+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
2019-07-09T02:04:00.301592+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "subdomain offset" to 2
2019-07-09T02:04:00.301714+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "trust proxy" to false
2019-07-09T02:04:00.302327+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "trust proxy fn" to [Function: trustNone]
2019-07-09T02:04:00.302464+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application booting in production mode
2019-07-09T02:04:00.302641+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "view" to [Function: View]
2019-07-09T02:04:00.302816+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "views" to '/app/server/views'
2019-07-09T02:04:00.302951+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "jsonp callback name" to 'callback'
2019-07-09T02:04:00.303102+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:00 GMT express:application set "view cache" to true
2019-07-09T02:04:05.185528+00:00 app[web.1]: 2019-07-09T02:04:05.185Z ioredis:redis status[****.redislabs.com:17618]: [empty] -> connecting
2019-07-09T02:04:05.187934+00:00 app[web.1]: 2019-07-09T02:04:05.187Z ioredis:redis queue command[****.redislabs.com:17618]: 0 -> subscribe([ 'livechat.send', 'livechat.stop' ])
2019-07-09T02:04:05.195850+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router use '/' query
2019-07-09T02:04:05.196138+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router:layer new '/'
2019-07-09T02:04:05.197250+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router use '/' expressInit
2019-07-09T02:04:05.197409+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router:layer new '/'
2019-07-09T02:04:05.197768+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router use '/' middleware
2019-07-09T02:04:05.197895+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router:layer new '/'
2019-07-09T02:04:05.198065+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router use '/' <anonymous>
2019-07-09T02:04:05.198178+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router:layer new '/'
2019-07-09T02:04:05.198339+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router use '/' <anonymous>
2019-07-09T02:04:05.198475+00:00 app[web.1]: Tue, 09 Jul 2019 02:04:05 GMT express:router:layer new '/'
2019-07-09T02:04:05.236264+00:00 app[web.1]: 2019-07-09T02:04:05.236Z ioredis:redis status[54.81.131.34:17618]: connecting -> connect
2019-07-09T02:04:05.237082+00:00 app[web.1]: 2019-07-09T02:04:05.236Z ioredis:redis write command[54.81.131.34:17618]: 0 -> info([])
2019-07-09T02:04:05.238167+00:00 app[web.1]: 2019-07-09T02:04:05.238Z ioredis:redis status[54.81.131.34:17618]: connecting -> connect
2019-07-09T02:04:05.238495+00:00 app[web.1]: 2019-07-09T02:04:05.238Z ioredis:redis write command[54.81.131.34:17618]: 0 -> info([])
2019-07-09T02:04:05.239371+00:00 app[web.1]: 2019-07-09T02:04:05.239Z ioredis:redis status[54.81.131.34:17618]: connecting -> connect
2019-07-09T02:04:05.239628+00:00 app[web.1]: 2019-07-09T02:04:05.239Z ioredis:redis write command[54.81.131.34:17618]: 0 -> info([])
2019-07-09T02:04:05.242284+00:00 app[web.1]: { ReplyError: NOAUTH Authentication required
2019-07-09T02:04:05.242286+00:00 app[web.1]:     at parseError (/app/server/node_modules/redis-parser/lib/parser.js:179:12)
2019-07-09T02:04:05.242288+00:00 app[web.1]:     at parseType (/app/server/node_modules/redis-parser/lib/parser.js:302:14) command: { name: 'info', args: [] } }
2019-07-09T02:04:05.243182+00:00 app[web.1]: [ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required
2019-07-09T02:04:05.243186+00:00 app[web.1]:     at parseError (/app/server/node_modules/redis-parser/lib/parser.js:179:12)
2019-07-09T02:04:05.243188+00:00 app[web.1]:     at parseType (/app/server/node_modules/redis-parser/lib/parser.js:302:14)
2019-07-09T02:04:05.244607+00:00 app[web.1]: (node:88) UnhandledPromiseRejectionWarning: Error: Redis subscribe failed: ReplyError: NOAUTH Authentication required
2019-07-09T02:04:05.244609+00:00 app[web.1]:     at n.subscribe (/app/server/dist/botium-box-server.js:1:55389)
2019-07-09T02:04:05.244611+00:00 app[web.1]:     at tryCatcher (/app/server/node_modules/standard-as-callback/built/utils.js:11:23)
2019-07-09T02:04:05.244613+00:00 app[web.1]:     at promise.then (/app/server/node_modules/standard-as-callback/built/index.js:30:51)
2019-07-09T02:04:05.244614+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-07-09T02:04:05.244860+00:00 app[web.1]: 2019-07-09T02:04:05.244Z botium-box-server-index WARNING { UnhandledPromiseRejectionWarning: Error: Redis subscribe failed: ReplyError: NOAUTH Authentication required
2019-07-09T02:04:05.244864+00:00 app[web.1]:     at n.subscribe (/app/server/dist/botium-box-server.js:1:55389)
2019-07-09T02:04:05.244866+00:00 app[web.1]:     at tryCatcher (/app/server/node_modules/standard-as-callback/built/utils.js:11:23)
2019-07-09T02:04:05.244868+00:00 app[web.1]:     at promise.then (/app/server/node_modules/standard-as-callback/built/index.js:30:51)
2019-07-09T02:04:05.244870+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-07-09T02:04:05.244872+00:00 app[web.1]:     at emitWarning (internal/process/promises.js:81:15)
2019-07-09T02:04:05.244874+00:00 app[web.1]:     at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
2019-07-09T02:04:05.244877+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:69:34) name: 'UnhandledPromiseRejectionWarning' }
2019-07-09T02:04:05.245013+00:00 app[web.1]: (node:88) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2019-07-09T02:04:05.245135+00:00 app[web.1]: 2019-07-09T02:04:05.244Z botium-box-server-index WARNING { Error: Redis subscribe failed: ReplyError: NOAUTH Authentication required
2019-07-09T02:04:05.245137+00:00 app[web.1]:     at n.subscribe (/app/server/dist/botium-box-server.js:1:55389)
2019-07-09T02:04:05.245139+00:00 app[web.1]:     at tryCatcher (/app/server/node_modules/standard-as-callback/built/utils.js:11:23)
2019-07-09T02:04:05.245141+00:00 app[web.1]:     at promise.then (/app/server/node_modules/standard-as-callback/built/index.js:30:51)
2019-07-09T02:04:05.245142+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7) name: 'UnhandledPromiseRejectionWarning' }
2019-07-09T02:04:05.245256+00:00 app[web.1]: (node:88) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-07-09T02:04:05.245429+00:00 app[web.1]: 2019-07-09T02:04:05.245Z botium-box-server-index WARNING { DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-07-09T02:04:05.245431+00:00 app[web.1]:     at emitDeprecationWarning (internal/process/promises.js:95:13)
2019-07-09T02:04:05.245433+00:00 app[web.1]:     at emitWarning (internal/process/promises.js:88:3)
2019-07-09T02:04:05.245434+00:00 app[web.1]:     at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
2019-07-09T02:04:05.245436+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:69:34) name: 'DeprecationWarning', code: 'DEP0018' }
2019-07-09T02:04:05.246273+00:00 app[web.1]: { ReplyError: NOAUTH Authentication required
2019-07-09T02:04:05.246275+00:00 app[web.1]:     at parseError (/app/server/node_modules/redis-parser/lib/parser.js:179:12)
2019-07-09T02:04:05.246277+00:00 app[web.1]:     at parseType (/app/server/node_modules/redis-parser/lib/parser.js:302:14) command: { name: 'info', args: [] } }
2019-07-09T02:04:05.248651+00:00 app[web.1]: 2019-07-09T02:04:05.248Z ioredis:redis status[54.81.131.34:17618]: connect -> close
2019-07-09T02:04:05.248853+00:00 app[web.1]: 2019-07-09T02:04:05.248Z ioredis:connection reconnect in 50ms
2019-07-09T02:04:05.249022+00:00 app[web.1]: 2019-07-09T02:04:05.248Z ioredis:redis status[54.81.131.34:17618]: close -> reconnecting
2019-07-09T02:04:05.249387+00:00 app[web.1]: 2019-07-09T02:04:05.249Z ioredis:redis status[54.81.131.34:17618]: connect -> close
2019-07-09T02:04:05.249522+00:00 app[web.1]: 2019-07-09T02:04:05.249Z ioredis:connection reconnect in 50ms
```

**Comment by codeforequity-at** [comment]
will check
