### ISSUE TITLE
I can't connect Prisma to Azure mysql

### ISSUE THREAD

**Issue by marcobocca1973** [codeforequity-at/botium-box-basic-dist#36]
Hi,

i have tried a lot bute every time I receive:

Exception in thread "main" java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host={{recmacmysql2.mysql.database.azure.com=null}=null})(port=3306)(type=master) : {{recmacmysql2.mysql.database.azure.com=null}=null}
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:161)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:79)
        at org.mari

.......................................
configmap.yml

  PRISMA_ENDPOINT: http://prisma:4466/box/ce13
  BOTIUMBOX_QUEUE_REDISURL: redis://redis:6379
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mysql
        host: {{ recmacmysql.mysql.database.azure.com }} 
        port: 3306
        user: {{ xxxxx }}
        password: {{ xxxxx}}
        migrations: true
..............................................................
I have checked mysql connection from other client and it works, I have checked firewall it's ok, why the connection

I'd like to try your product,it's very useful, please help me

Marco Bocca

**Comment by codeforequity-at** [comment]
Restarting the Prisma container usually helps. And you can try to increase the connectionLimit in the prisma configuration: https://www.prisma.io/forum/t/prisma-loses-connection-to-db/5764

**Comment by marcobocca1973** [comment]
Hi,

the problem is still present after

  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mysql
        host: {{ recmacmysql.mysql.database.azure.com }}
        port: 3306
        user: {{ xxxxx}}
        password: {{ xxxx}}
        migrations: true
        connectionLimit: 10

Could you tell me another tips, please ?

marco

**Comment by codeforequity-at** [comment]
Now I see that there are curly brackets in the PRISMA_CONFIG - they are meant to be part of the placeholders, so remove them please.

**Comment by marcobocca1973** [comment]
Hi,

It work for mysql but ...

![image](https://user-images.githubusercontent.com/47218182/75788438-89512580-5d68-11ea-98c8-afb1d567d5f8.png)

Could you help me ?

Thank you

marco

**Comment by codeforequity-at** [comment]
This is just a warning coming from Prisma, no need to worry as prisma is only accessible from within your docker network.

**Comment by marcobocca1973** [comment]
Thank you it works

**Comment by marcobocca1973** [comment]
Thank you it works
